spring:
  profiles:
    active: dev
  config:
    use-legacy-processing: true

server:
  port: 8081

quasar-fire:
  satellites:
    quantity: 3
    positions:
      0: -500,-200
      1: 100,-100
      2: 500,100